# -*- coding: utf-8 -*-
"""fish_rank

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-2y6g6xtEe8M52FtUZ0lzNwXS_hCdpy
"""

import pandas as pd
import numpy as np
import sys

kr = range(25,46)
kr = np.array(kr)
nb = range(22,86)
nb = np.array(nb)
rb = range(25,41)
rb = np.array(rb)
kb = range(24,41)
kb = np.array(kb)
rs = range(25,43)
rs = np.array(rs)

a = {'F':[np.percentile(kr, 0),np.percentile(nb, 0),np.percentile(rb, 0),np.percentile(kb, 0),np.percentile(rs, 0)],
                  'E':[np.percentile(kr, 20),np.percentile(nb, 20),np.percentile(rb, 20),np.percentile(kb, 20),np.percentile(rs, 20)],
                  'D':[np.percentile(kr, 40),np.percentile(nb, 40),np.percentile(rb, 40),np.percentile(kb, 40),np.percentile(rs, 40)],
                  'C':[np.percentile(kr, 60),np.percentile(nb, 60),np.percentile(rb, 60),np.percentile(kb, 60),np.percentile(rs, 60)],
                  'B':[np.percentile(kr, 80),np.percentile(nb, 80),np.percentile(rb, 80),np.percentile(kb, 80),np.percentile(rs, 80)],
                  'A':[np.percentile(kr, 100),np.percentile(nb,100),np.percentile(rb, 100),np.percentile(kb, 100),np.percentile(rs, 100)]}
df = pd.DataFrame(a, index = ['감성돔','넙치','돌돔','조피볼락','참돔']) # 어종별 길이 기준 백분위수(5)로 나눔 F:최소길이, A:최대길이

def get_rank(fish, size):
  
  
  df_fish = df.loc[[fish]]

  if size >= df_fish.loc[[fish],['F']].values[0,0]:
    rank = 'E'
  if size >= df_fish.loc[[fish],['E']].values[0,0]:
    rank = 'D'
  if size >= df_fish.loc[[fish],['D']].values[0,0]:
    rank = 'C'
  if size >= df_fish.loc[[fish],['C']].values[0,0]:
    rank = 'B'
  if size >= df_fish.loc[[fish],['B']].values[0,0]:
    rank = 'A'
  if size >= df_fish.loc[[fish],['A']].values[0,0]:
    rank = 'S'
  if size < df_fish.loc[[fish],['F']].values[0,0]:
    rank = 'F'

  return rank # S,A,B,C,D,E,'포획금지 사이즈' 7개 등급으로 나눔

fishType = sys.argv[1]
fishLength = sys.argv[2]

indexList = ['감성돔','넙치','돌돔','조피볼락','참돔']

감성돔,넙치,돌돔,조피볼락,참돔 = ['감성돔','넙치','돌돔','조피볼락','참돔']

def getFishType(fishType) :
  for i in indexList :
    if fishType == i :
      return i

matchFishType = getFishType(fishType)
matchFishLength = float(fishLength)

data = get_rank(matchFishType, matchFishLength) # (어종, 길이) 입력 시 등급 출력

utf8stdout = open(1, 'w', encoding='utf-8', closefd=False)
print(data, file=utf8stdout)